sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash -s -- --version v2.9.0

install: true

before_script:
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

script:
  - if jq '.extra.symfony.id != null' api/composer.json -e > /dev/null; then echo 'composer.json must not have symfony.id' 1>&2 && false; fi
  - docker-compose pull --ignore-pull-failures
  - docker-compose build --pull
  - docker-compose up -d
  - sleep 120
  - docker-compose exec -T php composer req sensiolabs/security-checker
  - docker-compose exec -T php bin/console security:check
#  - curl -f http://localhost # Client
#  - curl -f http://admin.localhost # Admin
#  - curl -f http://api.localhost # API
#  - curl -f http://stag.localhost # API
#  - curl -f http://dev.localhost  # API
#  - curl -fk https://localhost # Client (HTTP/2)
#  - curl -fk https://localhost:444 # Admin (HTTP/2)
#  - curl -fk https://localhost:8443 # API (HTTP/2)
#  - curl -fk https://localhost:8444 # Varnish (HTTP/2)
#  - helm lint ./api/helm/api/

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY"

deploy:
  provider: script
  script: docker-compose push
  skip_cleanup: true
  on:
    repo: ConductionNL/Proto-component-commonground
    branch: master
    
#deploy:
#  provider: script
#  script: docker-compose push test-pc-php 
#  skip_cleanup: true
#  on:
#    repo: ConductionNL/Proto-component-commonground
#    branch: testing
    
#deploy:
#  provider: script
#  script: docker-compose push dev-pc-php 
#  skip_cleanup: true
#  on:
#    repo: ConductionNL/Proto-component-commonground
#    branch: development
