name: Test

on:
    pull_request:
        branches:
            - dev-robert
    push:
        branches:
            - dev-robert

jobs:

    build:

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: |
               echo ::set-env name=APP_BUILD::$(grep APP_VERSION= .env | cut -d '=' -f2)
               echo echo "set APP_BUILD to $APP_BUILD"
              
